### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by pmarjora** [alimahmoudi29/arginfer#4]
I am trying to install this software for review purposes, but I am running into errors. I have tried both methods given on your installation pages and get slightly different errors each time (copied below). I should note that I am not a python user. I have installed python, but have not been able to update my version of pip (for reasons unknown), so perhaps it is possible that it is pip that is causing the problem here? I am running Mac OS X 10.14.6

[pms-mbp-2019:/usr/local/bin] pmarjora% python3 -m pip install arginfer --user
ERROR: Could not find a version that satisfies the requirement arginfer (from versions: none)
ERROR: No matching distribution found for arginfer

[pms-mbp-2019:/usr/local/bin] pmarjora% pip install -i https://test.pypi.org/simple/ arginfer
You are using pip version 7.0.1, however version 21.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting arginfer
  Downloading https://test-files.pythonhosted.org/packages/19/e8/805689ad02c045e62aaae1088e1fe6172c4af29ac3516921d6b28a7b2de2/arginfer-0.1.dev78.tar.gz (6.6MB)
    100% |████████████████████████████████| 6.6MB 90kB/s 
    Complete output from command python setup.py egg_info:
    Couldn't find index page for 'setuptools_scm' (maybe misspelled?)
    No local packages or download links found for setuptools-scm
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/qh/qw2c65v11w71z8bh6lsj16fw0000gp/T/pip-build-W6VDCw/arginfer/setup.py", line 49, in <module>
        "write_to": "arginfer/_version.py"},
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "build/bdist.macosx-10.10-x86_64/egg/setuptools/dist.py", line 268, in __init__
      File "build/bdist.macosx-10.10-x86_64/egg/setuptools/dist.py", line 313, in fetch_build_eggs
      File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 830, in resolve
      File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 1075, in best_match
      File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 1087, in obtain
      File "build/bdist.macosx-10.10-x86_64/egg/setuptools/dist.py", line 380, in fetch_build_egg
      File "build/bdist.macosx-10.10-x86_64/egg/setuptools/command/easy_install.py", line 623, in easy_install
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools-scm')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/qh/qw2c65v11w71z8bh6lsj16fw0000gp/T/pip-build-W6VDCw/arginfer

When I try to update pip, I get a similar error message:

[pms-mbp-2019:/usr/local/bin] pmarjora% pip install --upgrade pip
You are using pip version 7.0.1, however version 21.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pip
  Using cached https://files.pythonhosted.org/packages/52/e1/06c018197d8151383f66ebf6979d951995cf495629fc54149491f5d157d0/pip-21.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/qh/qw2c65v11w71z8bh6lsj16fw0000gp/T/pip-build-5v9C8D/pip/setup.py", line 7
        def read(rel_path: str) -> str:
                         ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/qh/qw2c65v11w71z8bh6lsj16fw0000gp/T/pip-build-5v9C8D/pip

**Comment by alimahmoudi29** [comment]
Dear @pmarjora 

I appreciate your interest in ARGinfer and am sorry for the inconvenience caused. Could you please try `pip install arginfer`? This should work. 

Regarding pip, I am afraid pip 7.0.1 is old and may not work for arginfer. Unfortunately, I do not know any solution other than  `pip install --upgrade pip`. This discussion may be helpful:  https://stackoverflow.com/questions/57062031/python-m-pip-install-upgrade-pip-does-not-work

Please let me know the issue persists. 
Regards,
Ali

**Comment by pmarjora** [comment]
That didn't quite work, I think because it keeps defaulting to p 7.0 even though I have updated to pip 24. But finally this seems to have worked:
python3 -m pip install arginfer
perhaps because it stops it using the old pip. Might be worth adding this as a thing to try when installing?
Thanks for your help.
