### ISSUE TITLE
Problem running ARGinfer

### ISSUE THREAD

**Issue by luishdez35** [alimahmoudi29/arginfer#5]
Hello, I try to run ARGinfer, but I have problems, when a put $arginfer the console show: 

Traceback (most recent call last):
  File "/opt/anaconda3/bin/arginfer", line 5, in <module>
    from arginfer.__main__ import main
  File "/opt/anaconda3/lib/python3.8/site-packages/arginfer/__init__.py", line 2, in <module>
    from arginfer.treeSequence import * # NOQA: F401, F403
  File "/opt/anaconda3/lib/python3.8/site-packages/arginfer/treeSequence.py", line 8, in <module>
    import msprime
  File "/opt/anaconda3/lib/python3.8/site-packages/msprime/__init__.py", line 36, in <module>
    from msprime.ancestry import (
  File "/opt/anaconda3/lib/python3.8/site-packages/msprime/ancestry.py", line 41, in <module>
    from . import demography as demog
  File "/opt/anaconda3/lib/python3.8/site-packages/msprime/demography.py", line 43, in <module>
    import demes
  File "/opt/anaconda3/lib/python3.8/site-packages/demes/__init__.py", line 9, in <module>
    from .demes import (
  File "/opt/anaconda3/lib/python3.8/site-packages/demes/demes.py", line 12, in <module>
    from .load_dump import dumps as demes_dumps
  File "/opt/anaconda3/lib/python3.8/site-packages/demes/load_dump.py", line 10, in <module>
    import ruamel.yaml
ModuleNotFoundError: No module named 'ruamel'

I hope you can help me, 

Thanks

**Comment by JereKoskela** [comment]
Hi Luis. It looks like you're missing the ruamel package, which is needed by demes, which is needed by msprime, on which ARGInfer depends. I think the problem should go away if you install the demes dependencies: https://github.com/popsim-consortium/demes-python/tree/0.1.1
